######################################################################
# Automatically generated by qmake (3.0) mar. mars 12 16:42:45 2013
######################################################################

TEMPLATE = app
TARGET = presidentReseau_Game
INCLUDEPATH += .

# Input
HEADERS += client.hpp mainwindow.hpp serverwindow.hpp
SOURCES += client.cpp main.cpp mainwindow.cpp serverwindow.cpp
